# Random
title:        Un posto a caso
url:          http://caprathebest.github.io
author:
  name:       'Gianluca Belardinelli'
  email:      'gianluca.beladirr2y@gmail.com'
# markdown:     rdiscount
#rdiscount:
#    extensions:
#        - generate_toc
permalink:    pretty
highlighter:  false
paginate:     5

# Google services
google_analytics: UA-81892472-1


# Global
exclude: ["start.bat"]

# Gems
gems: 				[jekyll-paginate]

# Serving
detach:  			false
port:    			4000
host:    			127.0.0.1
baseurl: 			""
show_dir_listing: 	false