title:        My blog
url:          http://caprathebest.github.io
version:      1.0
author:
  name:       'Gianluca Belardinelli'
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
